### ISSUE TITLE
runtime error when execute runtime --graph-file ./demo.yaml --runtime local

### ISSUE THREAD

**Issue by bobdingAI** [autocore-ai/zenoh_flow_autoware#26]
Hi,

I got this error when running 

 runtime --graph-file ./demo.yaml --runtime local

Here is the trace logs. My PC is  Ubuntu 20.04 with python 3.8.10 without any conda or venv.  Do you have any clue?

RUST_BACKTRACE=1 runtime --graph-file ./demo.yaml --runtime local
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: IOError("No such file or directory (os error 2)")', runtime/src/main.rs:91:87
stack backtrace:
   0: rust_begin_unwind
             at /rustc/22e491ac7ed454d34669151a8b6464cb643c9b41/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/22e491ac7ed454d34669151a8b6464cb643c9b41/library/core/src/panicking.rs:110:14
   2: core::result::unwrap_failed
             at /rustc/22e491ac7ed454d34669151a8b6464cb643c9b41/library/core/src/result.rs:1690:5
   3: runtime::main::main::{{closure}}
   4: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/22e491ac7ed454d34669151a8b6464cb643c9b41/library/core/src/future/mod.rs:84:19
   5: runtime::main::{{closure}}
             at /home/demo/.cargo/git/checkouts/zenoh-flow-examples-50c63331af8b4e8c/05526e0/runtime/src/main.rs:47:1
   6: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/22e491ac7ed454d34669151a8b6464cb643c9b41/library/core/src/future/mod.rs:84:19
   7: <async_std::task::builder::SupportTaskLocals<F> as core::future::future::Future>::poll::{{closure}}
             at /home/demo/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.9.0/src/task/builder.rs:199:17
   8: async_std::task::task_locals_wrapper::TaskLocalsWrapper::set_current::{{closure}}
             at /home/demo/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.9.0/src/task/task_locals_wrapper.rs:60:13
   9: std::thread::local::LocalKey<T>::try_with
             at /rustc/22e491ac7ed454d34669151a8b6464cb643c9b41/library/std/src/thread/local.rs:412:16
  10: std::thread::local::LocalKey<T>::with
             at /rustc/22e491ac7ed454d34669151a8b6464cb643c9b41/library/std/src/thread/local.rs:388:9
  11: async_std::task::task_locals_wrapper::TaskLocalsWrapper::set_current
             at /home/demo/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.9.0/src/task/task_locals_wrapper.rs:55:9
  12: <async_std::task::builder::SupportTaskLocals<F> as core::future::future::Future>::poll
             at /home/demo/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.9.0/src/task/builder.rs:197:13
  13: <futures_lite::future::Or<F1,F2> as core::future::future::Future>::poll
             at /home/demo/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-lite-1.12.0/src/future.rs:526:33
  14: async_executor::Executor::run::{{closure}}
             at /home/demo/.cargo/registry/src/github.com-1ecc6299db9ec823/async-executor-1.4.1/src/lib.rs:242:31
  15: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/22e491ac7ed454d34669151a8b6464cb643c9b41/library/core/src/future/mod.rs:84:19
  16: async_executor::LocalExecutor::run::{{closure}}
             at /home/demo/.cargo/registry/src/github.com-1ecc6299db9ec823/async-executor-1.4.1/src/lib.rs:447:33
  17: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/22e491ac7ed454d34669151a8b6464cb643c9b41/library/core/src/future/mod.rs:84:19
  18: async_io::driver::block_on
             at /home/demo/.cargo/registry/src/github.com-1ecc6299db9ec823/async-io-1.6.0/src/driver.rs:142:33
  19: async_global_executor::reactor::block_on::{{closure}}
             at /home/demo/.cargo/registry/src/github.com-1ecc6299db9ec823/async-global-executor-2.0.2/src/reactor.rs:3:18
  20: async_global_executor::reactor::block_on
             at /home/demo/.cargo/registry/src/github.com-1ecc6299db9ec823/async-global-executor-2.0.2/src/reactor.rs:12:5
  21: async_global_executor::executor::block_on::{{closure}}
             at /home/demo/.cargo/registry/src/github.com-1ecc6299db9ec823/async-global-executor-2.0.2/src/executor.rs:26:36
  22: std::thread::local::LocalKey<T>::try_with
             at /rustc/22e491ac7ed454d34669151a8b6464cb643c9b41/library/std/src/thread/local.rs:412:16
  23: std::thread::local::LocalKey<T>::with
             at /rustc/22e491ac7ed454d34669151a8b6464cb643c9b41/library/std/src/thread/local.rs:388:9
  24: async_global_executor::executor::block_on
             at /home/demo/.cargo/registry/src/github.com-1ecc6299db9ec823/async-global-executor-2.0.2/src/executor.rs:26:5
  25: async_std::task::builder::Builder::blocking::{{closure}}::{{closure}}
             at /home/demo/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.9.0/src/task/builder.rs:171:25
  26: async_std::task::task_locals_wrapper::TaskLocalsWrapper::set_current::{{closure}}
             at /home/demo/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.9.0/src/task/task_locals_wrapper.rs:60:13
  27: std::thread::local::LocalKey<T>::try_with
             at /rustc/22e491ac7ed454d34669151a8b6464cb643c9b41/library/std/src/thread/local.rs:412:16
  28: std::thread::local::LocalKey<T>::with
             at /rustc/22e491ac7ed454d34669151a8b6464cb643c9b41/library/std/src/thread/local.rs:388:9
  29: async_std::task::task_locals_wrapper::TaskLocalsWrapper::set_current
             at /home/demo/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.9.0/src/task/task_locals_wrapper.rs:55:9
  30: async_std::task::builder::Builder::blocking::{{closure}}
             at /home/demo/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.9.0/src/task/builder.rs:168:17
  31: std::thread::local::LocalKey<T>::try_with
             at /rustc/22e491ac7ed454d34669151a8b6464cb643c9b41/library/std/src/thread/local.rs:412:16
  32: std::thread::local::LocalKey<T>::with
             at /rustc/22e491ac7ed454d34669151a8b6464cb643c9b41/library/std/src/thread/local.rs:388:9
  33: async_std::task::builder::Builder::blocking
             at /home/demo/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.9.0/src/task/builder.rs:161:9
  34: async_std::task::block_on::block_on
             at /home/demo/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.9.0/src/task/block_on.rs:33:5
  35: runtime::main
             at /home/demo/.cargo/git/checkouts/zenoh-flow-examples-50c63331af8b4e8c/05526e0/runtime/src/main.rs:47:1
  36: core::ops::function::FnOnce::call_once
             at /rustc/22e491ac7ed454d34669151a8b6464cb643c9b41/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Aborted (core dumped)

**Comment by moelang** [comment]
The logs show problem at loading dynamic libs and creating dataflow, make sure `/opt/AutowareAuto` and `zenoh_flow_autoware/install` contains installed files and can be accessed.
![image](https://user-images.githubusercontent.com/7805397/150060264-99fdf027-e627-417d-bdd9-40b4c6d3cd9e.png)
![image](https://user-images.githubusercontent.com/7805397/150060645-331392e4-9b34-48e5-ae62-7efce9a8f957.png)
![image](https://user-images.githubusercontent.com/7805397/150060964-12940081-58cc-4274-b09c-1bd306e39f28.png)

And for crates version conflict, please check those crates in `Cargo.lock` file

```toml

[[package]]
name = "cxx"
version = "1.0.56"
source = "git+https://github.com/autocore-ai/cxx.git?branch=autocore-dev#5a6e73895801ca950150b613c9ff9e6461341acd"
dependencies = [
 "cc",
 "cxxbridge-flags",
 "cxxbridge-macro",
 "link-cplusplus",
]

[[package]]
name = "cxxbridge-flags"
version = "1.0.56"
source = "git+https://github.com/autocore-ai/cxx.git?branch=autocore-dev#5a6e73895801ca950150b613c9ff9e6461341acd"

[[package]]
name = "cxxbridge-macro"
version = "1.0.56"
source = "git+https://github.com/autocore-ai/cxx.git?branch=autocore-dev#5a6e73895801ca950150b613c9ff9e6461341acd"
dependencies = [
 "proc-macro2",
 "quote",
 "syn",
]

[[package]]
name = "zenoh-flow"
version = "0.1.0"
source = "git+https://github.com/autocore-ai/zenoh-flow.git?branch=autocore-dev#8639e04e5a27c2a94a5b7159945e09cbd72d2d3e"
dependencies = [
 "async-std",
 "async-trait",
 "base64",
 "bincode",
 "const_format",
 "derive_more",
 "env_logger",
 "event-listener",
 "flume",
 "futures",
 "futures-lite",
 "git-version",
 "libloading",
 "log",
 "paste",
 "petgraph",
 "pin-project-lite",
 "rustc_version 0.4.0",
 "serde",
 "serde_derive",
 "serde_json",
 "serde_yaml",
 "structopt",
 "typetag",
 "uhlc",
 "url",
 "uuid",
 "zenoh",
 "zenoh-flow-derive",
 "zenoh-util",
 "znrpc-macros",
 "zrpc",
]

[[package]]
name = "zenoh-flow-derive"
version = "0.0.1"
source = "git+https://github.com/autocore-ai/zenoh-flow.git?branch=autocore-dev#8639e04e5a27c2a94a5b7159945e09cbd72d2d3e"
dependencies = [
 "Inflector",
 "async-std",
 "darling",
 "futures",
 "proc-macro-error",
 "proc-macro2",
 "quote",
 "serde",
 "serde_derive",
 "syn",
 "syn-serde",
]
```
This is my `Cargo.lock` file:
[Cargo.zip](https://github.com/autocore-ai/zenoh_flow_autoware/files/7893593/Cargo.zip)
